FROM ubuntu

RUN apt-get update
RUN apt-get -yqq install curl git build-essential

# install node
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get -yqq install nodejs

WORKDIR /src

# install yarn and yarn install
RUN npm install -g yarn
RUN yarn
