/* Base styles thanks to Google's https://material.io/guidelines/components/cards.html */
export default {
  root: props => ({
    display: 'flex',
    flexDirection: 'column',
    width: '320px',
    height: 'auto',
    background: props.theme.colors.white,
    boxShadow: props.theme.globalBoxShadow,
    borderRadius: props.theme.globalBorderRadius,
    overflow: 'hidden',
  }),
  image: props => ({
    display: 'block',
    width: '320px',
    height: '196px',
    backgroundColor: props.theme.colors.primaryDark,
    backgroundImage: `url('${props.image}')`,
    backgroundSize: 'cover',
    backgroundPosition: 'center center',
  }),
  content: props => ({
    paddingTop: '24px',
    paddingRight: '16px',
    paddingBottom: '16px',
    paddingLeft: '16px',
  }),
  title: props => ({
    fontSize: '24px',
    lineHeight: '32px',
    fontWeight: '500',
    textTransform: 'capitalize',
    color: props.theme.typography.bodyColor,
    ...props.theme.typography.ellipsis,
  }),
  location: props => ({
    fontSize: '16px',
    lineHeight: '20px',
    fontWeight: '400',
    textTransform: 'capitalize',
    color: props.theme.typography.bodyColor,
    ...props.theme.typography.ellipsis,
  }),
  actions: props => ({
    color: props.theme.colors.gray600,
    textAlign: 'right',
    paddingTop: '8px',
    paddingRight: '8px',
    paddingBottom: '8px',
    paddingLeft: '8px',
  }),
};
