export default {
  root: props => ({
    width: '100%',
    maxWidth: '1200px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    minHeight: '100vh',
    margin: '0 auto',
    ...props.theme.globalPadding,
  }),
  header: props => ({
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '24px',
  }),
  city: props => ({
    display: 'flex',
    alignItems: 'center',
  }),
  text: props => ({
    fontSize: '24px',
    fontWeight: '700',
  }),
  switch: props => ({
    display: 'flex',
    padding: '2px',
    marginTop: '4px',
    marginLeft: '6px',
    fill: props.theme.colors.secondary,
  }),
  footer: props => ({
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderTop: `1px solid ${props.theme.colors.gray300}`,
    marginTop: '24px',
    paddingTop: '24px',
  }),
};
