module.exports = {
  atlanta: 'Atlanta',
  austin: 'Austin',
  boston: 'Boston',
  chicago: 'Chicago',
  dallas: 'Dallas',
  denver: 'Denver',
  detroit: 'Detroit',
  houston: 'Houston',
  lasvegas: 'Las Vegas',
  losangeles: 'Los Angeles',
  miami: 'Miami',
  minneapolis: 'Minneapolis',
  newyork: 'New York',
  orangecounty: 'Orange County',
  philadelphia: 'Philadelphia',
  phoenix: 'Phoenix',
  portland: 'Portland',
  raleigh: 'Raleigh',
  sacramento: 'Sacramento',
  sandiego: 'San Diego',
  seattle: 'Seattle',
  sfbay: 'San Francisco',
  washingtondc: 'Washington DC',
};
