export default {
  root: props => ({
    width: '100%',
    maxWidth: '1200px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    minHeight: '100vh',
    margin: '0 auto',
    ...props.theme.globalPadding,
  }),
  header: props => ({
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  }),
  logo: props => ({
    width: '300px',
    height: '120px',
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    cursor: 'default',
    userSelect: 'none',
  }),
  emoji: props => ({
    display: 'inline-block',
    width: '60px',
    fontSize: '40px',
    lineHeight: '60px',
    textAlign: 'center',
    transform: 'scale(2)',
  }),
};
